### ISSUE TITLE
Unable to Download the VUAMC.xml zip file and VU Amsterdam Metaphor Corpus (VUA).

### ISSUE THREAD

**Issue by WanzhengZhu** [EducationalTestingService/metaphor#2]
Unable to Download the [VUAMC.xml zip](http://ota.ahds.ac.uk/text/2541.zip) file and the [VU Amsterdam Metaphor Corpus](http://ota.ahds.ac.uk/headers/2541.xml) (VUA). The server can't be reached.

**Comment by WanzhengZhu** [comment]
Any update?

**Comment by benbuleong** [comment]
@WanzhengZhu, thanks for your interest in our metaphor research data! We are actually aware of the unavailability of the file, and are in discussions with VU Amsterdam on how to proceed. We apologize for the inconvenience caused, and hope to get back to you as soon as we have a resolution.

**Comment by Eternally1** [comment]
I have download the **VUA_corpus.zip** from this url(https://github.com/EducationalTestingService/metaphor/releases), but  this zip file needs the password for unzip, can you tell me?
