### ISSUE TITLE
VUAMC.xml missing

### ISSUE THREAD

**Issue by martialblog** [EducationalTestingService/metaphor#4]
Hi,

just saw that the XML file isn't available on the original site anymore, however, I was able to find a working link here:

https://web.archive.org/web/2019*/http://ota.ahds.ac.uk/headers/2541.xml

(I know this isn't technically an issue, but I wasn't sure if that should be mentioned in the README or not. If so, I can create a PR)

Regards, Markus

**Comment by benbuleong** [comment]
Thanks! But, the link seems not to be working now?

**Comment by martialblog** [comment]
Seems as if the link ota.ahds.ac.uk/headers/2541.xml is still down :crying_cat_face: But you can close the issue, I just wanted the information to be present in the repo.

**Comment by benbuleong** [comment]
I appreciate it. Thanks!

**Comment by benbuleong** [comment]
@martialblog We have just found another link based on yours that is active: https://web.archive.org/web/20191023211837/http://ota.ahds.ac.uk/headers/2541.xml

I tested and the VUAMC.xml is the same as the one we used for our experiments and in the shared task.

I have updated the page to reflect this new download link. Thanks again!
